import {
  Category,
  Equipment,
  User,
  Booking,
  Review,
  PaymentTransaction,
  Notification,
  ChatConversation,
  ChatMessage
} from '../types';
import {
  JOHN_DEERE_5310_IMAGE,
  JOHN_DEERE_5310_GALLERY,
  PREET_987_HARVESTER_IMAGE,
  PREET_987_HARVESTER_GALLERY,
  SHAKTIMAN_ROTAVATOR_IMAGE,
  SHAKTIMAN_ROTAVATOR_GALLERY,
  FIELDKING_SUPER_SEEDER_IMAGE,
  FIELDKING_SUPER_SEEDER_GALLERY,
  MAHINDRA_SARPANCH_IMAGE,
  MAHINDRA_SARPANCH_GALLERY,
  ASPEE_SPRAYER_IMAGE,
  ASPEE_SPRAYER_GALLERY,
  VST_SHAKTI_POWER_TILLER_IMAGE,
  VST_SHAKTI_POWER_TILLER_GALLERY,
  SWARAJ_855_FE_IMAGE,
  SWARAJ_855_FE_GALLERY,
  FIELDKING_DISC_PLOUGH_IMAGE,
  FIELDKING_DISC_PLOUGH_GALLERY,
  LASER_LAND_LEVELER_IMAGE,
  LASER_LAND_LEVELER_GALLERY,
  HYDRAULIC_TROLLEY_IMAGE,
  HYDRAULIC_TROLLEY_GALLERY,
  KUBOTA_MU4501_IMAGE,
  KUBOTA_MU4501_GALLERY
} from './machineryImages';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-tractors',
    name: 'Tractors',
    slug: 'tractors',
    description: '35 HP to 75+ HP utility and 4WD tractors with PTO & high pulling capacity',
    iconName: 'Tractor',
    imageUrl: JOHN_DEERE_5310_IMAGE,
    itemCount: 8,
    averageRatePerDay: 2400
  },
  {
    id: 'cat-harvesters',
    name: 'Harvesters & Combines',
    slug: 'harvesters',
    description: 'Self-propelled multi-crop combine harvesters for wheat, paddy, soybean & maize',
    iconName: 'Wheat',
    imageUrl: PREET_987_HARVESTER_IMAGE,
    itemCount: 4,
    averageRatePerDay: 7500
  },
  {
    id: 'cat-rotavators',
    name: 'Rotavators & Tillers',
    slug: 'rotavators',
    description: '5ft to 8ft rotary tillers for primary and secondary seedbed preparation',
    iconName: 'Cog',
    imageUrl: SHAKTIMAN_ROTAVATOR_IMAGE,
    itemCount: 6,
    averageRatePerDay: 1200
  },
  {
    id: 'cat-seeders',
    name: 'Seeders & Drills',
    slug: 'seeders',
    description: 'Super seeders, zero-till drills & pneumatic precision planters',
    iconName: 'Sprout',
    imageUrl: FIELDKING_SUPER_SEEDER_IMAGE,
    itemCount: 5,
    averageRatePerDay: 1400
  },
  {
    id: 'cat-ploughs',
    name: 'Ploughs & Cultivators',
    slug: 'ploughs',
    description: 'Reversible MB ploughs, disc ploughs, duckfoot & rigid tine cultivators',
    iconName: 'Shovel',
    imageUrl: FIELDKING_DISC_PLOUGH_IMAGE,
    itemCount: 5,
    averageRatePerDay: 900
  },
  {
    id: 'cat-sprayers',
    name: 'Boom Sprayers',
    slug: 'sprayers',
    description: 'Tractor-mounted boom sprayers, orchard mist blowers & high-pressure HTP pumps',
    iconName: 'Droplet',
    imageUrl: ASPEE_SPRAYER_IMAGE,
    itemCount: 4,
    averageRatePerDay: 1100
  },
  {
    id: 'cat-threshers',
    name: 'Threshers',
    slug: 'threshers',
    description: 'Multi-crop threshers with dual blowers for grain separation and straw making',
    iconName: 'Boxes',
    imageUrl: PREET_987_HARVESTER_IMAGE,
    itemCount: 3,
    averageRatePerDay: 1800
  },
  {
    id: 'cat-powertillers',
    name: 'Power Tillers',
    slug: 'power-tillers',
    description: '12-15 HP walking tractors ideal for wet puddling, vegetables & hilly plots',
    iconName: 'Gauge',
    imageUrl: VST_SHAKTI_POWER_TILLER_IMAGE,
    itemCount: 3,
    averageRatePerDay: 950
  },
  {
    id: 'cat-balers',
    name: 'Balers & Levelers',
    slug: 'balers-levelers',
    description: 'Laser land levelers & straw round/square balers for residue management',
    iconName: 'Compass',
    imageUrl: LASER_LAND_LEVELER_IMAGE,
    itemCount: 3,
    averageRatePerDay: 2200
  },
  {
    id: 'cat-trailers',
    name: 'Trolleys & Trailers',
    slug: 'trailers',
    description: 'Hydraulic tipping trolleys and heavy duty 2/4-wheel transport wagons',
    iconName: 'Truck',
    imageUrl: HYDRAULIC_TROLLEY_IMAGE,
    itemCount: 4,
    averageRatePerDay: 800
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'user-farmer-1',
    name: 'Amit Kumar',
    email: 'amit.farmer@agri.com',
    phone: '+91 98231 44556',
    role: 'FARMER',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    state: 'Maharashtra',
    district: 'Nagpur',
    village: 'Kalmeshwar',
    isVerified: true,
    isActive: true,
    bio: 'Farming 18 acres of soybean, cotton and wheat. Looking for dependable machinery during sowing and harvesting windows.',
    createdAt: '2026-01-10T09:00:00.000Z'
  },
  {
    id: 'user-owner-1',
    name: 'Rajesh Patil',
    email: 'rajesh.patil@agri.com',
    phone: '+91 94228 11223',
    role: 'OWNER',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    state: 'Maharashtra',
    district: 'Nagpur',
    village: 'Katol Road',
    isVerified: true,
    isActive: true,
    bio: 'Progressive grower & custom hiring center owner. Fleet of 3 tractors, 2 harvesters, and precision rotary equipment maintained regularly.',
    createdAt: '2025-11-15T10:00:00.000Z'
  },
  {
    id: 'user-owner-2',
    name: 'Gurpreet Singh Brar',
    email: 'gurpreet.brar@agri.com',
    phone: '+91 98140 77889',
    role: 'OWNER',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    state: 'Punjab',
    district: 'Ludhiana',
    village: 'Samrala',
    isVerified: true,
    isActive: true,
    bio: 'Heavy agricultural machinery fleet operator. Certified drivers provided with all heavy combine equipment.',
    createdAt: '2025-10-01T08:30:00.000Z'
  },
  {
    id: 'user-admin-1',
    name: 'Dr. R. K. Sharma',
    email: 'admin@krishimitra.gov.in',
    phone: '+91 98110 54321',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    state: 'Maharashtra',
    district: 'Nagpur',
    isVerified: true,
    isActive: true,
    bio: 'State Agriculture Extension Officer & Krishi Mitra Platform Moderator.',
    createdAt: '2025-01-01T00:00:00.000Z'
  }
];

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: 'eq-tractor-1',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    ownerRating: 4.9,
    ownerVerified: true,
    name: 'John Deere 5310 4WD PowerPro Tractor (55 HP)',
    categoryId: 'cat-tractors',
    categoryName: 'Tractors',
    brand: 'John Deere',
    model: '5310 PowerPro 4WD',
    manufacturingYear: 2024,
    horsepower: 55,
    fuelType: 'DIESEL',
    condition: 'EXCELLENT',
    description: 'Top-of-the-line 55 HP tractor equipped with dual clutch, power steering, reverse PTO, and 4WD drive. Excellent for heavy deep ploughing, super seeder operations, and wet puddling. Serviced every 250 hours with genuine John Deere parts.',
    specifications: {
      'Engine Power': '55 HP @ 2400 RPM (3 Cylinder Turbocharged)',
      'Transmission': '9 Forward + 3 Reverse CollarShift Synchromesh',
      'Lifting Capacity': '2000 kg with EQRL & Quick Hitch',
      'Fuel Tank': '68 Litres Low-Sulphur Diesel',
      'PTO Type': 'Dual Speed 540 & 540E Economy RPM',
      'Tire Size': 'Front 9.5x24, Rear 16.9x28 Heavy Radial'
    },
    images: JOHN_DEERE_5310_GALLERY,
    pricePerHour: 400,
    pricePerDay: 2500,
    pricePerWeek: 15500,
    securityDeposit: 2000,
    operatorAvailable: true,
    operatorCostPerDay: 500,
    location: 'Katol Road, Nagpur',
    district: 'Nagpur',
    state: 'Maharashtra',
    pincode: '440013',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.9,
    reviewCount: 28,
    totalRentals: 42,
    createdAt: '2026-01-05T10:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'eq-harvester-1',
    ownerId: 'user-owner-2',
    ownerName: 'Gurpreet Singh Brar',
    ownerPhone: '+91 98140 77889',
    ownerRating: 4.8,
    ownerVerified: true,
    name: 'Preet 987 Self-Propelled Multi-Crop Combine Harvester',
    categoryId: 'cat-harvesters',
    categoryName: 'Harvesters & Combines',
    brand: 'Preet',
    model: '987 Deluxe',
    manufacturingYear: 2023,
    horsepower: 101,
    fuelType: 'DIESEL',
    condition: 'EXCELLENT',
    description: 'Heavy duty combine harvester suitable for Wheat, Paddy, Soybean, Sunflower, and Mustard. 14-foot cutter bar ensures fast throughput of 4-5 acres per hour with minimum grain breakage (< 1%). Comes with experienced certified operator and helper.',
    specifications: {
      'Cutter Bar Width': '14 Feet (4.27 m) Heavy Reel',
      'Engine': '101 HP 6-Cylinder Water Cooled Turbo Diesel',
      'Grain Tank Capacity': '2.4 m³ (approx 1800 kg capacity)',
      'Cleaning Area': '2.8 m² adjustable dual sieve & blower',
      'Output Rate': '4.5 - 5.5 Acres/Hour under normal field conditions'
    },
    images: PREET_987_HARVESTER_GALLERY,
    pricePerHour: 1100,
    pricePerDay: 7800,
    pricePerWeek: 48000,
    securityDeposit: 5000,
    operatorAvailable: true,
    operatorCostPerDay: 0,
    location: 'Samrala Mandi, Ludhiana',
    district: 'Ludhiana',
    state: 'Punjab',
    pincode: '141114',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.8,
    reviewCount: 35,
    totalRentals: 58,
    createdAt: '2025-12-10T11:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'eq-rotavator-1',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    ownerRating: 4.9,
    ownerVerified: true,
    name: 'Shaktiman Semi-Champion 7-Feet Rotary Tiller (Rotavator)',
    categoryId: 'cat-rotavators',
    categoryName: 'Rotavators & Tillers',
    brand: 'Shaktiman',
    model: 'Semi Champion 7ft (54 Blades)',
    manufacturingYear: 2024,
    condition: 'EXCELLENT',
    description: 'Genuine Shaktiman Boron steel L-type 54 blades rotavator. Delivers fine pulverization in a single pass. Equipped with multi-speed gearbox compatible with 45 to 60 HP tractors with 540 RPM PTO.',
    specifications: {
      'Working Width': '7 Feet (210 cm working path)',
      'Blades': '54 Boron Steel L-Type Blades with Heat Treatment',
      'Gearbox': 'Multi-speed 4 Gear setup with side gear drive',
      'Required Tractor': '45 to 65 HP with standard 3-point linkage',
      'Depth of Cut': '6 to 8 inches adjustable skid shoes'
    },
    images: SHAKTIMAN_ROTAVATOR_GALLERY,
    pricePerHour: 200,
    pricePerDay: 1200,
    pricePerWeek: 7200,
    securityDeposit: 1500,
    operatorAvailable: false,
    operatorCostPerDay: 0,
    location: 'Kalmeshwar Road, Nagpur',
    district: 'Nagpur',
    state: 'Maharashtra',
    pincode: '441501',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.9,
    reviewCount: 19,
    totalRentals: 31,
    createdAt: '2026-01-12T14:30:00.000Z',
    isFeatured: true
  },
  {
    id: 'eq-seeder-1',
    ownerId: 'user-owner-2',
    ownerName: 'Gurpreet Singh Brar',
    ownerPhone: '+91 98140 77889',
    ownerRating: 4.8,
    ownerVerified: true,
    name: 'Fieldking Super Seeder 8-Feet (Paddy Straw Management)',
    categoryId: 'cat-seeders',
    categoryName: 'Seeders & Drills',
    brand: 'Fieldking',
    model: 'Super Seeder 11-Row',
    manufacturingYear: 2024,
    condition: 'EXCELLENT',
    description: 'Simultaneously tills standing paddy straw, seeds wheat, and deposits fertilizer in a single operation without burning residue. Saves diesel, time, and soil organic carbon.',
    specifications: {
      'Rows': '11 Rows seed & fertilizer calibrated delivery',
      'Working Width': '8 Feet (2.4 m heavy frame)',
      'Seed Metering': 'Fluted roller precision mechanism with depth adjustment',
      'Fertilizer Box': '120 kg capacity Stainless Steel hopper',
      'Required Tractor': '50+ HP with dual clutch & heavy lift'
    },
    images: FIELDKING_SUPER_SEEDER_GALLERY,
    pricePerHour: 250,
    pricePerDay: 1600,
    pricePerWeek: 9800,
    securityDeposit: 2000,
    operatorAvailable: true,
    operatorCostPerDay: 400,
    location: 'Ludhiana GT Road, Ludhiana',
    district: 'Ludhiana',
    state: 'Punjab',
    pincode: '141001',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.7,
    reviewCount: 14,
    totalRentals: 22,
    createdAt: '2026-01-18T09:15:00.000Z',
    isFeatured: false
  },
  {
    id: 'eq-tractor-2',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    ownerRating: 4.9,
    ownerVerified: true,
    name: 'Mahindra 575 DI Sarpanch 47 HP Utility Tractor',
    categoryId: 'cat-tractors',
    categoryName: 'Tractors',
    brand: 'Mahindra',
    model: '575 DI Sarpanch Plus',
    manufacturingYear: 2023,
    horsepower: 47,
    fuelType: 'DIESEL',
    condition: 'EXCELLENT',
    description: 'Fuel efficient 4-cylinder 47 HP tractor known for superior torque and reliability across all soil types. Perfect match for cultivator, MB plough, rotavator, and trolley haulage.',
    specifications: {
      'Engine Power': '47 HP @ 2100 RPM (2730 cc 4-Cylinder)',
      'Cylinders': '4 Cylinder naturally aspirated direct injection',
      'Hydraulics': '1600 kg high precision draft & position control',
      'Brakes': 'Oil Immersed Multi-disc heavy brakes'
    },
    images: MAHINDRA_SARPANCH_GALLERY,
    pricePerHour: 350,
    pricePerDay: 2200,
    pricePerWeek: 13500,
    securityDeposit: 2000,
    operatorAvailable: true,
    operatorCostPerDay: 450,
    location: 'Hingna Industrial Road, Nagpur',
    district: 'Nagpur',
    state: 'Maharashtra',
    pincode: '440028',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.8,
    reviewCount: 22,
    totalRentals: 36,
    createdAt: '2026-01-20T16:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'eq-sprayer-1',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    ownerRating: 4.9,
    ownerVerified: true,
    name: 'ASPEE Tractor Mounted 600-Litre Boom Sprayer',
    categoryId: 'cat-sprayers',
    categoryName: 'Boom Sprayers',
    brand: 'ASPEE',
    model: 'HTP 600L Boom 32ft',
    manufacturingYear: 2024,
    condition: 'EXCELLENT',
    description: '32-foot wingspan boom sprayer with 600-liter polyethylene tank and brass ceramic nozzles. Covers 40 acres in 4 hours with uniform droplet size. Ideal for cotton, soybean, pulses, and sugarcane crop protection.',
    specifications: {
      'Tank Volume': '600 Litres UV-stabilized rotational polyethylene',
      'Boom Width': '32 Feet (10 meters) foldable horizontal wings',
      'Nozzles': '20 Ceramic anti-drip nozzle tips with diaphragm check valves',
      'Operating Pressure': '40 - 60 PSI regulated via HTP triple-piston pump'
    },
    images: ASPEE_SPRAYER_GALLERY,
    pricePerHour: 180,
    pricePerDay: 1100,
    pricePerWeek: 6600,
    securityDeposit: 1500,
    operatorAvailable: false,
    operatorCostPerDay: 0,
    location: 'Katol Road, Nagpur',
    district: 'Nagpur',
    state: 'Maharashtra',
    pincode: '440013',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.6,
    reviewCount: 9,
    totalRentals: 15,
    createdAt: '2026-02-01T12:00:00.000Z',
    isFeatured: false
  },
  {
    id: 'eq-powertiller-1',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    ownerRating: 4.9,
    ownerVerified: true,
    name: 'VST Shakti 130 DI 13 HP Power Tiller',
    categoryId: 'cat-powertillers',
    categoryName: 'Power Tillers',
    brand: 'VST Shakti',
    model: '130 DI Plus',
    manufacturingYear: 2023,
    horsepower: 13,
    fuelType: 'DIESEL',
    condition: 'GOOD',
    description: 'Compact 13 HP walking power tiller with rotary blade assembly. Ideal for inter-cultivation in orchards, vegetable beds, and paddy puddling in small fragmented plots where large tractors cannot maneuver.',
    specifications: {
      'Power': '13 HP @ 2400 RPM Single Cylinder Water-Cooled Diesel',
      'Rotary Width': '600 mm adjustable rotary with 16 curved tines',
      'Fuel Consumption': '1.2 Litres/Hour ultra-frugal'
    },
    images: VST_SHAKTI_POWER_TILLER_GALLERY,
    pricePerHour: 150,
    pricePerDay: 950,
    pricePerWeek: 5700,
    securityDeposit: 1000,
    operatorAvailable: true,
    operatorCostPerDay: 350,
    location: 'Katol Road, Nagpur',
    district: 'Nagpur',
    state: 'Maharashtra',
    pincode: '440013',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.7,
    reviewCount: 11,
    totalRentals: 18,
    createdAt: '2026-01-25T08:00:00.000Z',
    isFeatured: false
  },
  {
    id: 'eq-tractor-3',
    ownerId: 'user-owner-2',
    ownerName: 'Gurpreet Singh Brar',
    ownerPhone: '+91 98140 77889',
    ownerRating: 4.8,
    ownerVerified: true,
    name: 'Swaraj 855 FE Heavy Duty 52 HP Tractor',
    categoryId: 'cat-tractors',
    categoryName: 'Tractors',
    brand: 'Swaraj',
    model: '855 FE 5-Star',
    manufacturingYear: 2024,
    horsepower: 52,
    fuelType: 'DIESEL',
    condition: 'EXCELLENT',
    description: 'Iconic Punjab agricultural workhorse with 3307 cc 3-cylinder engine. Legendary pulling power for laser land leveling, heavy disc harrow, and multi-speed rotavators.',
    specifications: {
      'Engine': '52 HP @ 2000 RPM (3307 cc Heavy Torque)',
      'Transmission': '8 Forward + 2 Reverse Centre Shift',
      'Hydraulics': '2000 kg Lift with Automatic Depth Control'
    },
    images: SWARAJ_855_FE_GALLERY,
    pricePerHour: 380,
    pricePerDay: 2400,
    pricePerWeek: 14800,
    securityDeposit: 2000,
    operatorAvailable: true,
    operatorCostPerDay: 500,
    location: 'Samrala Mandi, Ludhiana',
    district: 'Ludhiana',
    state: 'Punjab',
    pincode: '141114',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.9,
    reviewCount: 31,
    totalRentals: 47,
    createdAt: '2026-02-05T11:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'eq-plough-1',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    ownerRating: 4.9,
    ownerVerified: true,
    name: 'Fieldking Heavy Duty 3-Bottom Disc Plough',
    categoryId: 'cat-ploughs',
    categoryName: 'Ploughs & Cultivators',
    brand: 'Fieldking',
    model: 'Maxx Disc Plough 3B',
    manufacturingYear: 2024,
    condition: 'EXCELLENT',
    description: 'Heavy duty Boron steel discs designed for primary tillage in rocky, root-infested, and hard sticky soils where standard MB ploughs struggle. Inverts soil cleanly with minimal draft.',
    specifications: {
      'Discs': '3 Boron Steel 26-inch Concave Discs',
      'Frame': 'Seamless Heavy Duty Tubular Steel',
      'Required Tractor': '50 - 65 HP Tractor'
    },
    images: FIELDKING_DISC_PLOUGH_GALLERY,
    pricePerHour: 150,
    pricePerDay: 900,
    pricePerWeek: 5400,
    securityDeposit: 1000,
    operatorAvailable: false,
    operatorCostPerDay: 0,
    location: 'Kalmeshwar Road, Nagpur',
    district: 'Nagpur',
    state: 'Maharashtra',
    pincode: '441501',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.8,
    reviewCount: 16,
    totalRentals: 27,
    createdAt: '2026-02-08T09:30:00.000Z',
    isFeatured: false
  },
  {
    id: 'eq-baler-1',
    ownerId: 'user-owner-2',
    ownerName: 'Gurpreet Singh Brar',
    ownerPhone: '+91 98140 77889',
    ownerRating: 4.8,
    ownerVerified: true,
    name: 'Laser Land Leveler with Dual Mast Transmitter',
    categoryId: 'cat-balers',
    categoryName: 'Balers & Levelers',
    brand: 'Trimble Ag / Bharat',
    model: 'Laser Scraper Pro 8ft',
    manufacturingYear: 2024,
    condition: 'EXCELLENT',
    description: 'Precision laser-guided land leveler bucket. Reduces crop irrigation water requirement by 25-35%, increases fertilizer efficiency, and guarantees uniform crop stand across all plots.',
    specifications: {
      'Bucket Width': '8 Feet (2.4 m) Heavy Duty Cutting Edge',
      'Transmitter Range': '800 meters working diameter',
      'Hydraulic Control': 'Proportional fast response solenoid valve'
    },
    images: LASER_LAND_LEVELER_GALLERY,
    pricePerHour: 350,
    pricePerDay: 2200,
    pricePerWeek: 13200,
    securityDeposit: 2500,
    operatorAvailable: true,
    operatorCostPerDay: 500,
    location: 'Ludhiana GT Road, Ludhiana',
    district: 'Ludhiana',
    state: 'Punjab',
    pincode: '141001',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.9,
    reviewCount: 21,
    totalRentals: 34,
    createdAt: '2026-02-10T14:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'eq-trailer-1',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    ownerRating: 4.9,
    ownerVerified: true,
    name: 'Hydraulic Tipping 5-Ton Agricultural Tractor Trolley',
    categoryId: 'cat-trailers',
    categoryName: 'Trolleys & Trailers',
    brand: 'Mahalaxmi Trailers',
    model: '5-Ton Hydraulic Tipper',
    manufacturingYear: 2023,
    condition: 'EXCELLENT',
    description: 'Heavy duty 5-tonne capacity hydraulic tipping trolley with multi-stage telescopic jack, reinforced corrugated steel body, and heavy axle. Ideal for sugarcane, grain harvest, and manure transport.',
    specifications: {
      'Payload Capacity': '5 Tonnes (approx 100 quintals)',
      'Tipping': 'Rear Hydraulic Tipping with Heavy Ram',
      'Body Dimensions': '11 x 6.5 x 2.25 Feet'
    },
    images: HYDRAULIC_TROLLEY_GALLERY,
    pricePerHour: 120,
    pricePerDay: 800,
    pricePerWeek: 4800,
    securityDeposit: 1000,
    operatorAvailable: false,
    operatorCostPerDay: 0,
    location: 'Katol Road, Nagpur',
    district: 'Nagpur',
    state: 'Maharashtra',
    pincode: '440013',
    status: 'AVAILABLE',
    approvalStatus: 'APPROVED',
    rating: 4.7,
    reviewCount: 15,
    totalRentals: 26,
    createdAt: '2026-02-12T10:15:00.000Z',
    isFeatured: false
  },
  {
    id: 'eq-pending-1',
    ownerId: 'user-owner-2',
    ownerName: 'Gurpreet Singh Brar',
    ownerPhone: '+91 98140 77889',
    ownerRating: 4.8,
    ownerVerified: true,
    name: 'Kubota MU4501 4WD High Clearance Orchard Tractor',
    categoryId: 'cat-tractors',
    categoryName: 'Tractors',
    brand: 'Kubota',
    model: 'MU4501 4WD',
    manufacturingYear: 2025,
    horsepower: 45,
    fuelType: 'DIESEL',
    condition: 'EXCELLENT',
    description: 'Brand new Japanese technology Quad-4 engine 45 HP 4WD tractor. Outstanding fuel economy and compact turning radius. Awaiting admin inspection approval.',
    specifications: {
      'Engine': '45 HP 4-Cylinder E-CDIS Direct Injection',
      'Drive': '4 Wheel Drive with Bevel Gear Differential',
      'Hydraulics': '1640 kg capacity high speed lift'
    },
    images: KUBOTA_MU4501_GALLERY,
    pricePerHour: 380,
    pricePerDay: 2300,
    pricePerWeek: 14000,
    securityDeposit: 2000,
    operatorAvailable: true,
    operatorCostPerDay: 400,
    location: 'GT Road, Ludhiana',
    district: 'Ludhiana',
    state: 'Punjab',
    pincode: '141001',
    status: 'AVAILABLE',
    approvalStatus: 'PENDING',
    rating: 5.0,
    reviewCount: 0,
    totalRentals: 0,
    createdAt: '2026-08-10T10:00:00.000Z'
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-1001',
    bookingCode: 'KM-2026-1001',
    equipmentId: 'eq-tractor-1',
    equipmentName: 'John Deere 5310 4WD PowerPro Tractor (55 HP)',
    equipmentImage: JOHN_DEERE_5310_IMAGE,
    equipmentLocation: 'Katol Road, Nagpur',
    categoryId: 'cat-tractors',
    categoryName: 'Tractors',
    farmerId: 'user-farmer-1',
    farmerName: 'Amit Kumar',
    farmerPhone: '+91 98231 44556',
    farmerEmail: 'amit.farmer@agri.com',
    farmerLocation: 'Kalmeshwar, Nagpur, Maharashtra',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    startDate: '2026-07-20',
    endDate: '2026-07-23',
    durationDays: 3,
    pricePerDay: 2500,
    baseAmount: 7500,
    platformFee: 375, // 5%
    operatorIncluded: true,
    operatorAmount: 1500,
    securityDeposit: 2000,
    totalAmount: 9375,
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    paymentId: 'pay-txn-1001',
    razorpayOrderId: 'order_KM89123847',
    razorpayPaymentId: 'pay_KM992817263',
    paidAt: '2026-07-19T14:30:00.000Z',
    pickupAddress: 'Farm Plot 4, Katol Road, Nagpur (Near Primary Ag Co-op)',
    notes: 'Required for deep disc ploughing on 12 acres of black cotton soil.',
    createdAt: '2026-07-18T10:00:00.000Z',
    updatedAt: '2026-07-24T18:00:00.000Z'
  },
  {
    id: 'bk-1002',
    bookingCode: 'KM-2026-1002',
    equipmentId: 'eq-rotavator-1',
    equipmentName: 'Shaktiman Semi-Champion 7-Feet Rotary Tiller (Rotavator)',
    equipmentImage: SHAKTIMAN_ROTAVATOR_IMAGE,
    equipmentLocation: 'Kalmeshwar Road, Nagpur',
    categoryId: 'cat-rotavators',
    categoryName: 'Rotavators & Tillers',
    farmerId: 'user-farmer-1',
    farmerName: 'Amit Kumar',
    farmerPhone: '+91 98231 44556',
    farmerEmail: 'amit.farmer@agri.com',
    farmerLocation: 'Kalmeshwar, Nagpur, Maharashtra',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    startDate: '2026-08-16',
    endDate: '2026-08-18',
    durationDays: 2,
    pricePerDay: 1200,
    baseAmount: 2400,
    platformFee: 120,
    operatorIncluded: false,
    operatorAmount: 0,
    securityDeposit: 1500,
    totalAmount: 2520,
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    paymentId: 'pay-txn-1002',
    razorpayOrderId: 'order_KM99281721',
    razorpayPaymentId: 'pay_KM447192837',
    paidAt: '2026-08-13T11:00:00.000Z',
    pickupAddress: 'Kalmeshwar Machinery Hub, Nagpur',
    notes: 'Secondary seedbed preparation for rabi pulse crop.',
    createdAt: '2026-08-12T09:00:00.000Z',
    updatedAt: '2026-08-13T11:05:00.000Z'
  },
  {
    id: 'bk-1003',
    bookingCode: 'KM-2026-1003',
    equipmentId: 'eq-tractor-2',
    equipmentName: 'Mahindra 575 DI Sarpanch 47 HP Utility Tractor',
    equipmentImage: MAHINDRA_SARPANCH_IMAGE,
    equipmentLocation: 'Hingna Industrial Road, Nagpur',
    categoryId: 'cat-tractors',
    categoryName: 'Tractors',
    farmerId: 'user-farmer-1',
    farmerName: 'Amit Kumar',
    farmerPhone: '+91 98231 44556',
    farmerEmail: 'amit.farmer@agri.com',
    farmerLocation: 'Kalmeshwar, Nagpur, Maharashtra',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    ownerPhone: '+91 94228 11223',
    startDate: '2026-08-25',
    endDate: '2026-08-28',
    durationDays: 3,
    pricePerDay: 2200,
    baseAmount: 6600,
    platformFee: 330,
    operatorIncluded: true,
    operatorAmount: 1350,
    securityDeposit: 2000,
    totalAmount: 8280,
    status: 'PAYMENT_PENDING',
    paymentStatus: 'PENDING',
    ownerNotes: 'Request accepted. Machinery will be fueled and ready at Hingna Yard by 7:00 AM on August 25.',
    pickupAddress: 'Hingna Yard, Gate 2, Nagpur',
    notes: 'Inter-row cultivation and manure distribution.',
    createdAt: '2026-08-13T15:30:00.000Z',
    updatedAt: '2026-08-14T06:00:00.000Z'
  }
];

export const INITIAL_TRANSACTIONS: PaymentTransaction[] = [
  {
    id: 'pay-txn-1001',
    bookingId: 'bk-1001',
    bookingCode: 'KM-2026-1001',
    userId: 'user-farmer-1',
    userName: 'Amit Kumar',
    userRole: 'FARMER',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    amount: 9375,
    platformFee: 375,
    ownerNetEarnings: 9000,
    currency: 'INR',
    paymentMethod: 'RAZORPAY_UPI',
    razorpayPaymentId: 'pay_KM992817263',
    razorpayOrderId: 'order_KM89123847',
    status: 'PAID',
    createdAt: '2026-07-19T14:30:00.000Z'
  },
  {
    id: 'pay-txn-1002',
    bookingId: 'bk-1002',
    bookingCode: 'KM-2026-1002',
    userId: 'user-farmer-1',
    userName: 'Amit Kumar',
    userRole: 'FARMER',
    ownerId: 'user-owner-1',
    ownerName: 'Rajesh Patil',
    amount: 2520,
    platformFee: 120,
    ownerNetEarnings: 2400,
    currency: 'INR',
    paymentMethod: 'RAZORPAY_NETBANKING',
    razorpayPaymentId: 'pay_KM447192837',
    razorpayOrderId: 'order_KM99281721',
    status: 'PAID',
    createdAt: '2026-08-13T11:00:00.000Z'
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    bookingId: 'bk-1001',
    bookingCode: 'KM-2026-1001',
    equipmentId: 'eq-tractor-1',
    equipmentName: 'John Deere 5310 4WD PowerPro Tractor (55 HP)',
    reviewerId: 'user-farmer-1',
    reviewerName: 'Amit Kumar',
    reviewerRole: 'FARMER',
    revieweeId: 'user-owner-1',
    revieweeName: 'Rajesh Patil',
    rating: 5,
    comment: 'Tractor was in top condition with full tank. The 55 HP engine made quick work of deep ploughing on our 12-acre cotton plot. Owner Rajesh ji was very supportive and punctual.',
    createdAt: '2026-07-24T19:00:00.000Z'
  },
  {
    id: 'rev-2',
    bookingId: 'bk-historical-1',
    bookingCode: 'KM-2026-0941',
    equipmentId: 'eq-harvester-1',
    equipmentName: 'Preet 987 Self-Propelled Multi-Crop Combine Harvester',
    reviewerId: 'user-farmer-2',
    reviewerName: 'Sukhdev Singh',
    reviewerRole: 'FARMER',
    revieweeId: 'user-owner-2',
    revieweeName: 'Gurpreet Singh Brar',
    rating: 5,
    comment: 'Harvested 24 acres of wheat in two days. The Preet 987 operator was extremely skilled with zero grain loss. Escrow payment was very smooth and transparent.',
    createdAt: '2026-04-18T16:00:00.000Z'
  },
  {
    id: 'rev-3',
    bookingId: 'bk-historical-2',
    bookingCode: 'KM-2026-0812',
    equipmentId: 'eq-rotavator-1',
    equipmentName: 'Shaktiman Semi-Champion 7-Feet Rotary Tiller (Rotavator)',
    reviewerId: 'user-farmer-3',
    reviewerName: 'Vilasrao Shinde',
    reviewerRole: 'FARMER',
    revieweeId: 'user-owner-1',
    revieweeName: 'Rajesh Patil',
    rating: 5,
    comment: 'Very sharp blades and solid gearbox. Clean single-pass soil preparation. Highly recommended for cotton and soybean growers around Kalmeshwar.',
    createdAt: '2026-06-02T11:20:00.000Z'
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    userId: 'user-farmer-1',
    title: 'Booking Confirmed for Shaktiman Rotavator',
    message: 'Rajesh Patil has confirmed your booking KM-2026-1002 starting Aug 16, 2026.',
    type: 'BOOKING',
    isRead: false,
    link: '/farmer/bookings',
    createdAt: '2026-08-13T11:05:00.000Z'
  },
  {
    id: 'notif-2',
    userId: 'user-farmer-1',
    title: 'Payment Invoice Ready',
    message: 'Receipt for ₹2,520 (Booking KM-2026-1002) is now generated with GST breakdown.',
    type: 'PAYMENT',
    isRead: false,
    link: '/farmer/payment-history',
    createdAt: '2026-08-13T11:02:00.000Z'
  },
  {
    id: 'notif-3',
    userId: 'user-owner-1',
    title: 'New Rental Request Received',
    message: 'Amit Kumar requested Mahindra 575 DI for 3 days starting Aug 25.',
    type: 'BOOKING',
    isRead: false,
    link: '/owner/bookings',
    createdAt: '2026-08-13T15:30:00.000Z'
  },
  {
    id: 'notif-4',
    userId: 'user-admin-1',
    title: 'Pending Machinery Approval: Kubota MU4501',
    message: 'Gurpreet Singh Brar submitted a new 45 HP Kubota 4WD tractor listing for review.',
    type: 'EQUIPMENT',
    isRead: false,
    link: '/admin/machinery',
    createdAt: '2026-08-10T10:00:00.000Z'
  }
];

export const INITIAL_CONVERSATIONS: ChatConversation[] = [
  {
    id: 'conv-renter-owner-1',
    type: 'RENTER_OWNER',
    participants: [
      {
        id: 'user-farmer-1',
        name: 'Amit Kumar',
        role: 'FARMER',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        phone: '+91 98231 44556',
        location: 'Kalmeshwar, Nagpur',
        isOnline: true
      },
      {
        id: 'user-owner-1',
        name: 'Rajesh Patil',
        role: 'OWNER',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        phone: '+91 94228 11223',
        location: 'Katol Road, Nagpur',
        isOnline: true
      }
    ],
    equipmentId: 'eq-tractor-1',
    equipmentName: 'John Deere 5310 4WD PowerPro Tractor (55 HP)',
    equipmentImage: JOHN_DEERE_5310_IMAGE,
    equipmentRate: 2400,
    bookingId: 'bk-001',
    bookingCode: 'KM-2026-1001',
    topic: 'John Deere 5310 Rental & Driver Inquiries',
    lastMessage: 'Received and accepted your booking. We will dispatch the tractor to your field location Wednesday evening.',
    lastMessageSenderId: 'user-owner-1',
    lastMessageTime: '2026-08-16T14:45:00.000Z',
    unreadCountForUser: {
      'user-farmer-1': 1,
      'user-owner-1': 0
    },
    createdAt: '2026-08-16T09:30:00.000Z',
    updatedAt: '2026-08-16T14:45:00.000Z'
  },
  {
    id: 'conv-admin-renter-1',
    type: 'ADMIN_RENTER',
    participants: [
      {
        id: 'user-farmer-1',
        name: 'Amit Kumar',
        role: 'FARMER',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        phone: '+91 98231 44556',
        location: 'Kalmeshwar, Nagpur',
        isOnline: true
      },
      {
        id: 'user-admin-1',
        name: 'Dr. R. K. Sharma',
        role: 'ADMIN',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
        phone: '+91 98110 54321',
        location: 'Krishi Bhavan, Nagpur (Govt Ext Desk)',
        isOnline: true
      }
    ],
    topic: 'Official Escrow Protection & Mahadbt CHC Subsidy Claim',
    lastMessage: 'All digital receipts from Krishi Mitra are GST-compliant and eligible for up to 40% State CHC custom hiring subsidy.',
    lastMessageSenderId: 'user-admin-1',
    lastMessageTime: '2026-08-15T16:20:00.000Z',
    unreadCountForUser: {
      'user-farmer-1': 0,
      'user-admin-1': 0
    },
    createdAt: '2026-08-15T11:00:00.000Z',
    updatedAt: '2026-08-15T16:20:00.000Z'
  },
  {
    id: 'conv-renter-owner-2',
    type: 'RENTER_OWNER',
    participants: [
      {
        id: 'user-farmer-1',
        name: 'Amit Kumar',
        role: 'FARMER',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        phone: '+91 98231 44556',
        location: 'Kalmeshwar, Nagpur',
        isOnline: true
      },
      {
        id: 'user-owner-2',
        name: 'Gurpreet Singh Brar',
        role: 'OWNER',
        avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
        phone: '+91 98140 77889',
        location: 'Samrala, Ludhiana',
        isOnline: false
      }
    ],
    equipmentId: 'eq-harvester-1',
    equipmentName: 'Preet 987 Self-Propelled Multi-Crop Combine Harvester',
    equipmentImage: PREET_987_HARVESTER_IMAGE,
    equipmentRate: 7500,
    topic: 'Combine Harvester Multi-Crop & Trailer Delivery',
    lastMessage: 'Yes, we bring the harvester on a flatbed trailer within 25 km at no extra transit fee.',
    lastMessageSenderId: 'user-owner-2',
    lastMessageTime: '2026-08-14T10:15:00.000Z',
    unreadCountForUser: {
      'user-farmer-1': 0,
      'user-owner-2': 0
    },
    createdAt: '2026-08-14T08:00:00.000Z',
    updatedAt: '2026-08-14T10:15:00.000Z'
  },
  {
    id: 'conv-admin-owner-1',
    type: 'ADMIN_OWNER',
    participants: [
      {
        id: 'user-owner-1',
        name: 'Rajesh Patil',
        role: 'OWNER',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        phone: '+91 94228 11223',
        location: 'Katol Road, Nagpur',
        isOnline: true
      },
      {
        id: 'user-admin-1',
        name: 'Dr. R. K. Sharma',
        role: 'ADMIN',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
        phone: '+91 98110 54321',
        location: 'Krishi Bhavan, Nagpur (Govt Ext Desk)',
        isOnline: true
      }
    ],
    topic: 'Custom Hiring Center Fleet Verification & Escrow Payouts',
    lastMessage: 'RC documents verified! Your equipment is now displayed with the Green Verified Fleet badge.',
    lastMessageSenderId: 'user-admin-1',
    lastMessageTime: '2026-08-12T18:00:00.000Z',
    unreadCountForUser: {
      'user-owner-1': 0,
      'user-admin-1': 0
    },
    createdAt: '2026-08-12T14:00:00.000Z',
    updatedAt: '2026-08-12T18:00:00.000Z'
  }
];

export const INITIAL_MESSAGES: ChatMessage[] = [
  // Conversation 1: Amit Kumar (Farmer) & Rajesh Patil (Owner)
  {
    id: 'msg-101',
    conversationId: 'conv-renter-owner-1',
    senderId: 'user-farmer-1',
    senderName: 'Amit Kumar',
    senderRole: 'FARMER',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-owner-1',
    receiverName: 'Rajesh Patil',
    receiverRole: 'OWNER',
    content: 'Namaste Rajesh ji! I am preparing our 15-acre plot in Kalmeshwar for Rabi wheat sowing. Is your 55 HP John Deere 5310 tractor available for 4 days next week?',
    createdAt: '2026-08-16T09:30:00.000Z',
    isRead: true
  },
  {
    id: 'msg-102',
    conversationId: 'conv-renter-owner-1',
    senderId: 'user-owner-1',
    senderName: 'Rajesh Patil',
    senderRole: 'OWNER',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-farmer-1',
    receiverName: 'Amit Kumar',
    receiverRole: 'FARMER',
    content: 'Namaste Amit ji! Yes, the 5310 PowerPro 4WD is available starting Thursday. It was serviced last week, with fresh engine oil and sharp hydraulic hitch pins.',
    createdAt: '2026-08-16T09:42:00.000Z',
    isRead: true
  },
  {
    id: 'msg-103',
    conversationId: 'conv-renter-owner-1',
    senderId: 'user-farmer-1',
    senderName: 'Amit Kumar',
    senderRole: 'FARMER',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-owner-1',
    receiverName: 'Rajesh Patil',
    receiverRole: 'OWNER',
    content: 'Can you also send an experienced driver who knows deep MB ploughing and rotavator operations?',
    createdAt: '2026-08-16T10:10:00.000Z',
    isRead: true
  },
  {
    id: 'msg-104',
    conversationId: 'conv-renter-owner-1',
    senderId: 'user-owner-1',
    senderName: 'Rajesh Patil',
    senderRole: 'OWNER',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-farmer-1',
    receiverName: 'Amit Kumar',
    receiverRole: 'FARMER',
    content: 'Yes, our certified tractor driver Vinod (₹450/day) has 8+ years experience. He will operate the machinery carefully. Diesel will be as per your actual field meter reading.',
    createdAt: '2026-08-16T10:30:00.000Z',
    isRead: true
  },
  {
    id: 'msg-105',
    conversationId: 'conv-renter-owner-1',
    senderId: 'user-farmer-1',
    senderName: 'Amit Kumar',
    senderRole: 'FARMER',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-owner-1',
    receiverName: 'Rajesh Patil',
    receiverRole: 'OWNER',
    content: 'Submitting booking KM-2026-1001 with 100% Escrow Protection right now. Please confirm once visible on your dashboard.',
    createdAt: '2026-08-16T14:15:00.000Z',
    isRead: true
  },
  {
    id: 'msg-106',
    conversationId: 'conv-renter-owner-1',
    senderId: 'user-owner-1',
    senderName: 'Rajesh Patil',
    senderRole: 'OWNER',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-farmer-1',
    receiverName: 'Amit Kumar',
    receiverRole: 'FARMER',
    content: 'Received and accepted your booking. We will dispatch the tractor to your field location Wednesday evening.',
    createdAt: '2026-08-16T14:45:00.000Z',
    isRead: false
  },

  // Conversation 2: Amit Kumar (Farmer) & Dr. R. K. Sharma (Admin Support)
  {
    id: 'msg-201',
    conversationId: 'conv-admin-renter-1',
    senderId: 'user-admin-1',
    senderName: 'Dr. R. K. Sharma',
    senderRole: 'ADMIN',
    senderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-farmer-1',
    receiverName: 'Amit Kumar',
    receiverRole: 'FARMER',
    content: 'Namaste Amit ji, welcome to the Krishi Mitra Agri-Support & Grievance desk. How may we assist your farming operations or equipment rentals today?',
    createdAt: '2026-08-15T11:00:00.000Z',
    isRead: true
  },
  {
    id: 'msg-202',
    conversationId: 'conv-admin-renter-1',
    senderId: 'user-farmer-1',
    senderName: 'Amit Kumar',
    senderRole: 'FARMER',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-admin-1',
    receiverName: 'Dr. R. K. Sharma',
    receiverRole: 'ADMIN',
    content: 'Respected Sir, I wanted to know if rental payments made on Krishi Mitra are covered by government subsidy or if we can upload the rental receipt to Mahadbt / SMAM portal?',
    createdAt: '2026-08-15T11:35:00.000Z',
    isRead: true
  },
  {
    id: 'msg-203',
    conversationId: 'conv-admin-renter-1',
    senderId: 'user-admin-1',
    senderName: 'Dr. R. K. Sharma',
    senderRole: 'ADMIN',
    senderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-farmer-1',
    receiverName: 'Amit Kumar',
    receiverRole: 'FARMER',
    content: 'All digital receipts from Krishi Mitra are GST-compliant and eligible for up to 40% State CHC custom hiring subsidy. Download the PDF invoice from your Farmer Dashboard under "Payment History" and submit it with your 7/12 extract.',
    createdAt: '2026-08-15T16:20:00.000Z',
    isRead: true
  },

  // Conversation 3: Amit Kumar & Gurpreet Singh Brar (Owner)
  {
    id: 'msg-301',
    conversationId: 'conv-renter-owner-2',
    senderId: 'user-farmer-1',
    senderName: 'Amit Kumar',
    senderRole: 'FARMER',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-owner-2',
    receiverName: 'Gurpreet Singh Brar',
    receiverRole: 'OWNER',
    content: 'Sat Sri Akal Gurpreet ji, is your Preet combine harvester available for 20 acres soybean harvesting in early October?',
    createdAt: '2026-08-14T08:00:00.000Z',
    isRead: true
  },
  {
    id: 'msg-302',
    conversationId: 'conv-renter-owner-2',
    senderId: 'user-owner-2',
    senderName: 'Gurpreet Singh Brar',
    senderRole: 'OWNER',
    senderAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-farmer-1',
    receiverName: 'Amit Kumar',
    receiverRole: 'FARMER',
    content: 'Sat Sri Akal Amit ji! Yes, we have two trained drivers and straw chopper attachment equipped. Can easily cover 10-12 acres per day.',
    createdAt: '2026-08-14T09:10:00.000Z',
    isRead: true
  },
  {
    id: 'msg-303',
    conversationId: 'conv-renter-owner-2',
    senderId: 'user-farmer-1',
    senderName: 'Amit Kumar',
    senderRole: 'FARMER',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-owner-2',
    receiverName: 'Gurpreet Singh Brar',
    receiverRole: 'OWNER',
    content: 'What is the transport/unloading arrangement for reaching Kalmeshwar?',
    createdAt: '2026-08-14T09:45:00.000Z',
    isRead: true
  },
  {
    id: 'msg-304',
    conversationId: 'conv-renter-owner-2',
    senderId: 'user-owner-2',
    senderName: 'Gurpreet Singh Brar',
    senderRole: 'OWNER',
    senderAvatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-farmer-1',
    receiverName: 'Amit Kumar',
    receiverRole: 'FARMER',
    content: 'Yes, we bring the harvester on a flatbed trailer within 25 km at no extra transit fee.',
    createdAt: '2026-08-14T10:15:00.000Z',
    isRead: true
  },

  // Conversation 4: Rajesh Patil & Dr. R. K. Sharma (Admin)
  {
    id: 'msg-401',
    conversationId: 'conv-admin-owner-1',
    senderId: 'user-owner-1',
    senderName: 'Rajesh Patil',
    senderRole: 'OWNER',
    senderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-admin-1',
    receiverName: 'Dr. R. K. Sharma',
    receiverRole: 'ADMIN',
    content: 'Respected Dr. Sharma, I have submitted the RC registration and fitness certificate for our Custom Hiring Center fleet. Kindly verify our owner profile.',
    createdAt: '2026-08-12T14:00:00.000Z',
    isRead: true
  },
  {
    id: 'msg-402',
    conversationId: 'conv-admin-owner-1',
    senderId: 'user-admin-1',
    senderName: 'Dr. R. K. Sharma',
    senderRole: 'ADMIN',
    senderAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80',
    receiverId: 'user-owner-1',
    receiverName: 'Rajesh Patil',
    receiverRole: 'OWNER',
    content: 'RC documents verified! Your equipment is now displayed with the Green Verified Fleet badge.',
    createdAt: '2026-08-12T18:00:00.000Z',
    isRead: true
  }
];
