import { Router } from 'express';
import { z } from 'zod';
import { supabaseAdmin } from '../config/supabase.js';
import { requireAuth, requireRole, AuthRequest } from '../middleware/auth.js';
import { equipmentToFrontend } from '../utils/mappers.js';
import { ok, fail } from '../utils/http.js';

const router=Router();
const equipmentSchema=z.object({name:z.string().min(2),categoryId:z.string().optional(),categoryName:z.string().optional(),description:z.string().optional(),brand:z.string().optional(),model:z.string().optional(),manufacturingYear:z.coerce.number().int().min(1900).max(2100).optional(),horsepower:z.coerce.number().nonnegative().optional(),fuelType:z.enum(['DIESEL','ELECTRIC','PETROL','MANUAL']).optional(),condition:z.enum(['EXCELLENT','GOOD','FAIR']).default('GOOD'),specifications:z.record(z.string(),z.string()).default({}),images:z.array(z.string()).default([]),pricePerHour:z.coerce.number().nonnegative().default(0),pricePerDay:z.coerce.number().nonnegative(),pricePerWeek:z.coerce.number().nonnegative().optional(),securityDeposit:z.coerce.number().nonnegative().default(0),operatorAvailable:z.boolean().default(false),operatorCostPerDay:z.coerce.number().nonnegative().default(0),bookingAmount:z.coerce.number().nonnegative().default(0),location:z.string().min(1),district:z.string().min(1),state:z.string().min(1),pincode:z.string().min(3),status:z.enum(['AVAILABLE','MAINTENANCE','INACTIVE']).default('AVAILABLE'),isFeatured:z.boolean().optional()});
const baseSelect='*, owner:profiles!equipment_owner_id_fkey(id,full_name,phone,is_verified), category:categories(id,name)';

router.get('/',async(req,res,next)=>{try{let q=supabaseAdmin.from('equipment').select(baseSelect,{count:'exact'}).eq('is_active',true).eq('approval_status','APPROVED').eq('availability_status','AVAILABLE'); const {search,category,location,state,district,minPrice,maxPrice,condition,operatorRequired,startDate,endDate,sortBy}=req.query as Record<string,string>; if(search) q=q.or(`name.ilike.%${search}%,brand.ilike.%${search}%,model.ilike.%${search}%,category_name.ilike.%${search}%,location.ilike.%${search}%,district.ilike.%${search}%,state.ilike.%${search}%`); if (category && category !== 'all') {
  q = q.eq('category_id', category);
} if(state) q=q.eq('state',state); if(district) q=q.eq('district',district); if(location&&location!=='all') q=q.ilike('location',`%${location}%`); if(minPrice)q=q.gte('daily_rate',Number(minPrice)); if(maxPrice)q=q.lte('daily_rate',Number(maxPrice)); if(condition&&condition!=='ALL')q=q.eq('condition',condition); if(operatorRequired==='true')q=q.eq('operator_available',true); if(sortBy==='price_low')q=q.order('daily_rate',{ascending:true}); else if(sortBy==='price_high')q=q.order('daily_rate',{ascending:false}); else if(sortBy==='rating')q=q.order('rating',{ascending:false}); else q=q.order('created_at',{ascending:false}); const {data,error,count}=await q; if(error)return fail(res,error.message,500); let items=(data??[]).map(equipmentToFrontend); if(startDate&&endDate){const {data:busy}=await supabaseAdmin.from('bookings').select('equipment_id,start_date,end_date').in('status',['PENDING','PAYMENT_PENDING','CONFIRMED','ACTIVE']); const ids=new Set((busy??[]).filter((b:any)=>startDate<=b.end_date&&endDate>=b.start_date).map((b:any)=>b.equipment_id)); items=items.filter((e:any)=>!ids.has(e.id));} return ok(res,{items,total:count??items.length});}catch(e){next(e)}});
router.get('/categories',async(_req,res,next)=>{try{const {data,error}=await supabaseAdmin.from('categories').select('*').order('name'); if(error)return fail(res,error.message,500); return ok(res,{categories:(data??[]).map((c:any)=>({id:c.id,name:c.name,slug:c.slug,description:c.description??'',iconName:c.icon_name??'Tractor',imageUrl:c.image_url??'',itemCount:c.item_count??0,averageRatePerDay:Number(c.average_rate_per_day??0)}))});}catch(e){next(e)}});

router.post('/images',requireAuth,requireRole('OWNER','ADMIN'),async(req:AuthRequest,res,next)=>{try{const i=z.object({dataUrl:z.string().min(20),fileName:z.string().optional()}).parse(req.body);const match=i.dataUrl.match(/^data:(image\/[^;]+);base64,(.+)$/);if(!match)return fail(res,'Only base64 image data URLs are supported for upload.',400);const contentType=match[1];const buffer=Buffer.from(match[2],'base64');if(buffer.length>5*1024*1024)return fail(res,'Image must be 5 MB or smaller.',400);const safe=(i.fileName??'equipment-image').replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${req.user!.id}/${Date.now()}-${safe}`;const {error}=await supabaseAdmin.storage.from('equipment-images').upload(path,buffer,{contentType,upsert:false});if(error)return fail(res,error.message,400);const {data}=supabaseAdmin.storage.from('equipment-images').getPublicUrl(path);return ok(res,{url:data.publicUrl,path});}catch(e){next(e)}});
router.delete('/images',requireAuth,requireRole('OWNER','ADMIN'),async(req:AuthRequest,res)=>{const path=String(req.query.path||'');if(!path||(!path.startsWith(`${req.user!.id}/`)&&req.user!.role!=='ADMIN'))return fail(res,'Invalid storage path.',403);const {error}=await supabaseAdmin.storage.from('equipment-images').remove([path]);if(error)return fail(res,error.message,400);return ok(res,{});});
router.get('/owner/:ownerId',requireAuth,async(req:AuthRequest,res,next)=>{try{if(req.user!.role!=='ADMIN'&&req.user!.id!==req.params.ownerId)return fail(res,'Forbidden.',403);const {data,error}=await supabaseAdmin.from('equipment').select(baseSelect).eq('owner_id',req.params.ownerId).order('created_at',{ascending:false});if(error)return fail(res,error.message,500);return ok(res,{items:(data??[]).map(equipmentToFrontend)});}catch(e){next(e)}});
router.get('/admin',requireAuth,requireRole('ADMIN'),async(_req,res,next)=>{try{const {data,error}=await supabaseAdmin.from('equipment').select(baseSelect).order('created_at',{ascending:false});if(error)return fail(res,error.message,500);return ok(res,{items:(data??[]).map(equipmentToFrontend)});}catch(e){next(e)}});
router.get('/:id',async(req,res)=>{const {data,error}=await supabaseAdmin.from('equipment').select(baseSelect).eq('id',req.params.id).single();if(error||!data)return fail(res,'Equipment not found.',404);return ok(res,{equipment:equipmentToFrontend(data)});});
router.post('/',requireAuth,requireRole('OWNER'),async(req:AuthRequest,res,next)=>{try{const i=equipmentSchema.parse(req.body);const row:any={owner_id:req.user!.id,name:i.name,category_id:i.categoryId??null,category_name:i.categoryName??'',description:i.description??'',brand:i.brand??'',model:i.model??'',manufacturing_year:i.manufacturingYear??new Date().getFullYear(),horsepower:i.horsepower??null,fuel_type:i.fuelType??null,condition:i.condition,specifications:i.specifications,image_urls:i.images,daily_rate:i.pricePerDay,price_per_hour:i.pricePerHour,price_per_week:i.pricePerWeek??i.pricePerDay*7,security_deposit:i.securityDeposit,operator_available:i.operatorAvailable,operator_cost_per_day:i.operatorCostPerDay,booking_amount:i.bookingAmount,location:i.location,district:i.district,state:i.state,pincode:i.pincode,availability_status:i.status,approval_status:'PENDING',is_active:true,is_featured:i.isFeatured??false};const {data,error}=await supabaseAdmin.from('equipment').insert(row).select(baseSelect).single();if(error)return fail(res,error.message,400);return ok(res,{equipment:equipmentToFrontend(data)},201);}catch(e){next(e)}});
router.put('/:id',requireAuth,async(req:AuthRequest,res,next)=>{try{const current=await supabaseAdmin.from('equipment').select('*').eq('id',req.params.id).single();if(current.error||!current.data)return fail(res,'Equipment not found.',404);if(req.user!.role!=='ADMIN'&&current.data.owner_id!==req.user!.id)return fail(res,'You can only update your own equipment.',403);const i=equipmentSchema.partial().parse(req.body);const row:any={};const map:any={name:'name',categoryId:'category_id',categoryName:'category_name',description:'description',brand:'brand',model:'model',manufacturingYear:'manufacturing_year',horsepower:'horsepower',fuelType:'fuel_type',condition:'condition',specifications:'specifications',images:'image_urls',pricePerDay:'daily_rate',pricePerHour:'price_per_hour',pricePerWeek:'price_per_week',securityDeposit:'security_deposit',operatorAvailable:'operator_available',operatorCostPerDay:'operator_cost_per_day',bookingAmount:'booking_amount',location:'location',district:'district',state:'state',pincode:'pincode',status:'availability_status',isFeatured:'is_featured'};Object.entries(i).forEach(([k,v])=>row[map[k]]=v); if(req.user!.role!=='ADMIN')row.approval_status='PENDING';const {data,error}=await supabaseAdmin.from('equipment').update(row).eq('id',req.params.id).select(baseSelect).single();if(error)return fail(res,error.message,400);return ok(res,{equipment:equipmentToFrontend(data)});}catch(e){next(e)}});
router.delete('/:id',requireAuth,async(req:AuthRequest,res)=>{const current=await supabaseAdmin.from('equipment').select('owner_id').eq('id',req.params.id).single();if(current.error||!current.data)return fail(res,'Equipment not found.',404);if(req.user!.role!=='ADMIN'&&current.data.owner_id!==req.user!.id)return fail(res,'Forbidden.',403);const {error}=await supabaseAdmin.from('equipment').update({is_active:false,availability_status:'INACTIVE'}).eq('id',req.params.id);if(error)return fail(res,error.message,400);return ok(res,{});});
router.patch('/:id/status',requireAuth,requireRole('OWNER','ADMIN'),async(req:AuthRequest,res)=>{const schema=z.object({status:z.enum(['AVAILABLE','MAINTENANCE','INACTIVE'])});const {status}=schema.parse(req.body);const current=await supabaseAdmin.from('equipment').select('owner_id').eq('id',req.params.id).single();if(current.error||!current.data)return fail(res,'Equipment not found.',404);if(req.user!.role==='OWNER'&&current.data.owner_id!==req.user!.id)return fail(res,'Forbidden.',403);const {data,error}=await supabaseAdmin.from('equipment').update({availability_status:status}).eq('id',req.params.id).select(baseSelect).single();if(error)return fail(res,error.message,400);return ok(res,{equipment:equipmentToFrontend(data)});});
router.get('/:id/availability',async(req,res)=>{const schema=z.object({startDate:z.string(),endDate:z.string()});const {startDate,endDate}=schema.parse(req.query);const {data,error}=await supabaseAdmin.from('bookings').select('start_date,end_date').eq('equipment_id',req.params.id).in('status',['PENDING','PAYMENT_PENDING','CONFIRMED','ACTIVE']);if(error)return fail(res,error.message,500);const available=!(data??[]).some((b:any)=>startDate<=b.end_date&&endDate>=b.start_date);return ok(res,{available});});
export default router;
