export const USER_ROLES = {
  FARMER: 'FARMER',
  OWNER: 'OWNER',
  ADMIN: 'ADMIN'
} as const;

export type UserRole = typeof USER_ROLES[keyof typeof USER_ROLES];

export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
  HANDOVER_PENDING: 'HANDOVER_PENDING',
  ACTIVE: 'ACTIVE',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  INSPECTION_PENDING: 'INSPECTION_PENDING',
  COMPLETED: 'COMPLETED',
  DISPUTED: 'DISPUTED',
  EXPIRED: 'EXPIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED'
} as const;

export type BookingStatus = typeof BOOKING_STATUS[keyof typeof BOOKING_STATUS];

export const PAYMENT_STATUS = {
  CREATED: 'CREATED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
} as const;

export const MACHINERY_STATUS = {
  AVAILABLE: 'AVAILABLE',
  MAINTENANCE: 'MAINTENANCE',
  INACTIVE: 'INACTIVE'
} as const;

export const VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED'
} as const;

export const PLATFORM_CONFIG = {
  COMMISSION_PERCENTAGE: 0, // Fee is calculated from total rental amount by slab.
  MIN_COMMISSION_INR: 0,
  DEFAULT_SEARCH_RADIUS_KM: 50
};
