import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { ENV } from './config/env.js';
import authRoutes from './routes/auth.js';
import equipmentRoutes from './routes/equipment.js';
import bookingRoutes from './routes/bookings.js';
import notificationRoutes from './routes/notifications.js';
import chatRoutes from './routes/chat.js';
import reviewRoutes from './routes/reviews.js';
import disputeRoutes from './routes/disputes.js';
import favoriteRoutes from './routes/favorites.js';
import adminRoutes from './routes/admin.js';
import paymentRoutes from './routes/payments.js';
import translationRoutes from './routes/translations.js';
import { errorHandler } from './middleware/errorHandler.js';


export const app = express();
app.use(helmet());
app.use(cors({ origin: ENV.FRONTEND_URL === '*' ? true : ENV.FRONTEND_URL, credentials: true }));
app.use(express.json({ limit: '5mb', verify: (req: any, _res, buf) => { req.rawBody = Buffer.from(buf); } }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-7', legacyHeaders: false }));
app.get('/api/health', (_req, res) => res.json({ success: true, data: { status: 'healthy', service: 'KrishiMitra API', payments: true, timestamp: new Date().toISOString() } }));
app.use('/api/auth', authRoutes);
app.use('/api/equipment', equipmentRoutes);
app.use('/api/bookings', bookingRoutes);
app.use('/api/notifications', notificationRoutes);
app.use('/api/chat', chatRoutes);
app.use('/api/conversations', chatRoutes);
app.use('/api/messages', chatRoutes);
app.use('/api/reviews', reviewRoutes);
app.use('/api/disputes', disputeRoutes);
app.use('/api/favorites', favoriteRoutes);
app.use('/api/admin', adminRoutes);
app.use('/api/payments', paymentRoutes);
app.use('/api/translations', translationRoutes);
app.use('/api/translation', translationRoutes);
app.use('/api', (_req, res) => res.status(404).json({ success: false, message: 'The requested API endpoint does not exist.' }));
app.use(errorHandler);
